import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { ReleaseDecisionBadge } from "@/components/release-decision-badge";
import { WorkspaceSetupError } from "@/components/workspace-setup-error";
import { ensureDefaultProject } from "@/lib/evalgate/default-project";

const metrics = [["Total test cases", "—"], ["Active prompt versions", "—"], ["Total eval runs", "—"], ["Pass rate", "—%"], ["Blocked releases", "—"], ["Average score", "—"], ["Safety failures", "—"]] as const;
export default async function DashboardPage() {
  const workspace = await ensureDefaultProject();
  if (!workspace.ok) return <WorkspaceSetupError />;

  return <><PageHeader eyebrow="Overview" title="Release readiness dashboard" description="A high-level view of evaluation coverage, quality, and the latest gate decision." /><section className="panel mt-7 p-6"><p className="eyebrow">Workspace</p><div className="mt-3 grid gap-5 sm:grid-cols-2"><div><h2 className="text-lg font-semibold text-white">{workspace.project.name}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{workspace.project.description}</p></div><div className="sm:text-right"><p className="text-xs uppercase tracking-wider text-slate-500">Signed in as</p><p className="mt-2 text-sm font-medium text-slate-200">{workspace.email}</p></div></div><p className="mt-5 border-t border-slate-800 pt-4 text-xs text-slate-500">Evaluation data and live workspace metrics will appear in later phases.</p></section><div className="mt-6 rounded-lg border border-teal-400/20 bg-teal-400/5 px-4 py-3 text-xs text-teal-200"><strong>Skeleton data:</strong> all metric values remain empty until dashboard queries are implemented in a later phase.</div><section aria-label="Evaluation metrics" className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value]) => <MetricCard key={label} label={label} value={value} detail="Placeholder · no live data" />)}<article className="panel p-5 sm:col-span-2 xl:col-span-1"><p className="text-sm font-medium text-slate-400">Latest release decision</p><div className="mt-4"><ReleaseDecisionBadge /></div><p className="mt-4 text-xs text-slate-500">Placeholder · run history unavailable</p></article></section><section className="panel mt-6 p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-white">Recent evaluation activity</h2><p className="mt-1 text-sm text-slate-500">Completed runs will appear here.</p></div><span className="rounded bg-slate-800 px-2 py-1 text-xs text-slate-500">Coming later</span></div><div className="mt-6 border-t border-dashed border-slate-800 pt-8 text-center text-sm text-slate-500">No evaluation runs to display.</div></section></>;
}
